# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
- page: 主页
  url: /
  icon:
- page: 时间轴
  url: /archives/
  icon:
- page: java
  url: /categories/java/
  icon:
- page: k8s
  url: /categories/k8s/
  icon:
- page: 分布式
  url: /categories/分布式/
  icon:
- page: 杂七杂八
  url: /categories/杂七杂八/
  icon:
- page: 关于我
  url: /about/
  icon:

## favicon
favicon: /favicon.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: '/img/head-img.jpg'
  url: 'https://promotion.aliyun.com/ntms/yunparter/invite.html?userCode=be5loode'

# 各个小工具的设置

## widgets
widgets:
  - search
  - notification
  - friends
  - social
  - category
  - archive
  - tagcloud


## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: false
    tags: false

## 网站公告设置
notification: |-
            <p>
                声明：本站所有内容为个人学习笔记
            </p>


## 友链设置
links:
  - k8s: http://devops.k8s.icql.work
  - jenkins: http://devops.jenkins.icql.work
  - frp: http://devops.frp.icql.work
  - archive: http://archive.icql.work
  - file: http://file.icql.work

## 社交设置
social:
 - name: 邮箱
   icon: envelope
   href: mailto:chenqinglin@hnu.edu.cn
 - name: Github
   icon: github
   href: https://github.com/icql
 - name: Gitee
   icon: fa-github-alt
   href: https://gitee.com/icql

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   format: 'YYYY年MM月'
   show_count: true
   order: -1

## 标签云设置
tagcloud:
  tag3d: false
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false


# 主题自定义个性化配置

## 网站宣传语
branding: 

## 设置banner背景图片
banner:
    img: '/img/banner.jpg'

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

## 截取文章首页描述字数
excerptLength: 120

## 是否开启文章目录
toc: true

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 900
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="mailto:chenqinglin@hnu.edu.cn" target="_blank">ICQL</a>

## 文章打赏
reward:
#  alipay: ''
  wepay: '/img/reward-wepay.jpg'
  tip: 赞赏是不耍流氓的鼓励

## 主题评论

## Valine评论
valine:
   enable: true
   appId: 190OpkcEkSQnJAx6hIAE7AWK-gzGzoHsz
   appKey: OOaiLWcbssoHKHjhYhnLGmye
   placeholder: 说点什么吧
   notify: true
   verify: false
   avatar: mm
   meta: nick,mail
   pageSize: 10

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid:
  conf:

### 来必力
livere:
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

## Gitalk评论
gitalk:
   enable: false
   clientID:
   clientSecret:
   repo:
   owner:
   admin:
   perPage:
   distractionFreeMode: true

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### gitment评论(长期不更新，不建议使用)
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422


## 网站访客统计
visit_counter:
   site: true
   page: true

## 网站访问统计分析

### 网盟CNZZ统计
cnzz_analytics: 1263868967

### 百度统计
baidu_analytics:

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics:

### 百度站点认证
baidu_site_verification:

### 百度自动推送
baidu_push: true

#网站配置
since: 2017 - 2020
subject: ICQL
ICP: 闽ICP备18024992号-1

robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.3
